DATA:
  datasets:
    AssemblyHands:
      aliases:
      - assemblyhands
      splits:
        train_stage1:
        - /data_0/renkaiwen/webdatasets2_remake/AssemblyHands/train_stage1/*.tar
        train_stage2:
        - /data_0/renkaiwen/webdatasets2_remake/AssemblyHands/train_stage2/*.tar
        val_stage1:
        - /data_0/renkaiwen/webdatasets2_remake/AssemblyHands/val_stage1/*.tar
        val_stage2:
        - /data_0/renkaiwen/webdatasets2_remake/AssemblyHands/val_stage2/*.tar
    DexYCB:
      aliases:
      - dexycb
      splits:
        train_stage1:
        - /data_0/renkaiwen/webdatasets2_remake/DexYCB/train_stage1/*.tar
        train_stage2:
        - /data_0/renkaiwen/webdatasets2_remake/DexYCB/train_stage2/*.tar
    FreiHAND:
      aliases:
      - freihand
      splits:
        train_stage1:
        - /data_0/renkaiwen/webdatasets2_remake/FreiHAND/train_stage1/*.tar
    HO3D_v3:
      aliases:
      - ho3d
      splits:
        train_stage1:
        - /data_0/renkaiwen/webdatasets2_remake/HO3D_v3/train_stage1/*.tar
        train_stage2:
        - /data_0/renkaiwen/webdatasets2_remake/HO3D_v3/train_stage2/*.tar
    HOT3D:
      aliases:
      - hot3d
      splits:
        train_stage1:
        - /data_0/renkaiwen/webdatasets2_remake/HOT3D/train_stage1/*.tar
        train_stage2:
        - /data_0/renkaiwen/webdatasets2_remake/HOT3D/train_stage2/*.tar
    InterHand2.6M:
      aliases:
      - ih26m
      splits:
        train_stage1:
        - /data_0/renkaiwen/webdatasets2_remake/InterHand2.6M/train_stage1/*.tar
        train_stage2:
        - /data_0/renkaiwen/webdatasets2_remake/InterHand2.6M/train_stage2/*.tar
    MTC:
      aliases:
      - mtc
      splits:
        train_stage1:
        - /data_0/renkaiwen/webdatasets2_remake/MTC/train_stage1/*.tar
        train_stage2:
        - /data_0/renkaiwen/webdatasets2_remake/MTC/train_stage2/*.tar
    RHD:
      aliases:
      - rhd
      splits:
        train_stage1:
        - /data_0/renkaiwen/webdatasets2_remake/RHD/train_stage1/*.tar
  train:
    split: train_stage1
    stride: 1
    filter:
      enabled: true
      min_valid_joints_2d: 16
      min_hand_bbox_edge_px: 8
      frame_policy: all
    groups:
      ego:
        weight: 0.2
        datasets:
          HOT3D: 0.5
          AssemblyHands: 0.5
      aux:
        weight: 0.8
        datasets:
          InterHand2.6M: 0.25
          FreiHAND: 0.1875
          MTC: 0.1875
          DexYCB: 0.125
          HO3D_v3: 0.125
          RHD: 0.125
    shardshuffle: 64
    post_clip_shuffle: 64
    sampling:
      mode: random_clip
      clips_per_sequence: 1
  val:
    source:
    - /data_0/renkaiwen/webdatasets2_remake/AssemblyHands/val_stage1/*.tar
    stride: 1
    filter:
      enabled: false
      min_valid_joints_2d: 16
      min_hand_bbox_edge_px: 8
      frame_policy: all
    full_eval: false
    max_val_step: 1000
    sampling:
      mode: dense
      shardshuffle: false
      post_clip_shuffle: 0
    batch_size: 16
  test:
    source: []
    stride: 1
    filter:
      enabled: false
      min_valid_joints_2d: 16
      min_hand_bbox_edge_px: 8
      frame_policy: all
    full_eval: false
    sampling:
      mode: dense
      shardshuffle: false
      post_clip_shuffle: 0
MODEL:
  img_size: 224
  img_mean:
  - 0.485
  - 0.456
  - 0.406
  img_std:
  - 0.229
  - 0.224
  - 0.225
  stage: stage1
  stage1_weight: null
  num_frame: 1
  joint_type: '3'
  norm_by_hand: false
  backbone:
    backbone_str: model/facebook/dinov2-large
    infusion_layer: null
    drop_cls: false
    kwargs: {}
  handec:
    num_layer: 4
    num_head: 16
    dim_head: 64
    dim_mlp: 4096
    dropout: 0.1
    norm: layer
    context_dim: 1024
    skip_token_embed: false
    use_mean_init: false
    denorm_output: false
    cam_head_type: patch_uv_rho_multibin
    heatmap_resolution:
    - 512
    - 512
    - 1024
    root_z:
      num_bins: 8
      d_min: -0.71
      d_max: 0.75
      prior_k: 121.0
      geom_hidden_dim: 256
      dropout: 0.1
      use_data_source_embed: false
  persp_info_embed:
    type: ca
    num_sample: 8
    pie_fusion: all
  temporal_encoder:
    num_layer: 2
    num_head: 16
    trope_scalar: 20.0
    zero_linear: true
LOSS:
  lambda_theta: 3.0
  lambda_shape: 3.0
  lambda_uv_patch: 1.0
  lambda_trans: 0.001
  lambda_root_z_cls: 1.0
  lambda_root_z_res: 1.0
  lambda_rel: 0.012
  lambda_img: 0.002
  supervise_heatmap: true
  heatmap_sigma: 4.0
  pred_joint_z_min_mm: 20.0
  reproj_loss_type: robust_l1
  reproj_loss_delta: 84.0
  root_filter:
    min_valid_joints_2d: 16
    min_hand_bbox_edge_px: 8
TRACKER:
  enabled: true
  type: swanlab
  project: cs-vit2-remake
  workspace: mine268
  mode: cloud
  print_to_console: true
  log_images: true
GENERAL:
  description: stage1 no_norm patch_uv_rho_multibin
  total_step: 100000
  log_step: 5
  vis_step: 100
  checkpoint_step: 5000
  warmup_step: 5000
  dropout_warmup_step: 10000
  cosine_cycle: 0.4
  num_worker: 2
  prefetch_factor: 1
  seed: 3229084
  val_seed: 42
  resume_path: null
TRAIN:
  lr: 0.0001
  backbone_lr: 1.0e-05
  grad_accum_step: 1
  max_grad: 1.0
  weight_decay: 0.0001
  sample_per_device: 32
  mixed_precision: bf16
  expansion_ratio: 2.0
  scale_z_range:
  - 1.0
  - 1.0
  scale_f_range:
  - 1.0
  - 1.0
  persp_rot_max: 0.0872664626
  perspective_normalization: false
  augmentation:
    color_jitter:
      enabled: true
      brightness: 0.2
      contrast: 0.2
      saturation: 0.1
      hue: 0.0
      p: 0.5
    gaussian_noise:
      enabled: true
      mean: 0.0
      std: 0.03
      p: 0.5
TEST:
  output_dir: output/test_results
  batch_size: 16
  save_format: hdf5
  compression: gzip
  max_samples: null
  vis_step: 100
  enable_vis: true
  checkpoint_path: null
